config/routes.rb
Rails.application.routes.draw do
 
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'homes#top'
    resources :genres, except: [:show, :destroy, :new]
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders
    resources :order_details, only:[:update]
  end
  
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
  
  namespace :public do
    get 'orders/thanks', to: 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders
    resources :items, only: [:index, :show]
    resources :customers,except: [:new, :index]
    resources :addresses,except: [:new, :show]
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :cart_items, except: [:show, :new, :edit] 
    delete 'cart_items' => 'cart_items#destroy_all'
  end

end

app/models/address.rb
class Address < ApplicationRecord
 
  belongs_to :customer
  
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  
  def address_display
     '〒' + postal_code + ' ' + address + ' ' + name
  end  
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

 belongs_to :customer
 belongs_to :item
 
 
 
 def with_tax_price
   (price*1.1).floor
 end  
   
 #小計
 def subtotal
     item.with_tax_price*amount
 end
 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         
   has_many :cart_items, dependent: :destroy
   has_many :addresses, dependent: :destroy
   has_many :orders, dependent: :destroy 
   
   validates :last_name, presence: true
   validates :first_name, presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :postal_code, presence: true
   validates :telephone_number, presence: true
   validates :address, presence: true
   
   # def active_for_authentication?
   #   super && (is_deleted == true)
   #end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :ites,dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

 has_many :order_details, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 
 
 belongs_to :genre
 has_one_attached :image
 
  
  validates :name, presence: true
  validates :price, presence: true
  
  def with_tax_price
   (price * 1.1).floor
  end
  
  
  
end

app/models/order.rb
class Order < ApplicationRecord
 
 has_many :order_details, dependent: :destroy
 belongs_to :customer
 
 validates :postal_code, presence: true
 validates :address, presence: true
 validates :name, presence: true
 validates :way_of_paying, presence: true
    
 enum way_of_paying: { credit_card: 0, transfer: 1}
 enum recieve_status: { payment_waiting: 0, payment_finish:1, production: 2, ready_to_delivery: 3,delivery_finish: 4}
 
  
 def with_tax_price
   (price*1.1).floor
 end  
   
 #小計
 def subtotal
     item.with_tax_price*amount
 end
 
 def sum_order_price
   subtotal+shipping_fee
 end 
 
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    
    enum production_status:{ not_yet:0, waiting:1, working:2, complete:3}
    
    
     def subtotal
     item.with_tax_price*amount
     end
     
end     

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    
   def index    
     @customers = Customer.all
   end
   
   def show
     @customer = Customer.find(params[:id])
   end 
  def edit
     @customer = Customer.find(params[:id])
  end 
  
  def update
     @customer = Customer.find(params[:id])
     if @customer.update(customer_params)
        redirect_to admin_customers_path(@customer)
     else
        render :edit
     end   
  end
   
   
    private
   
   def customer_params
     params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
   end 
   
   
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    
    def index
      @genre = Genre.new
      
      @genres = Genre.all
      
    end 
    
    def create
      @genre = Genre.new(genre_params)
     if @genre.save
      redirect_to admin_genres_path
     else
        flash[:alert]= "もう一度入力してね"
        @genres = Genre.all
        render:index
     end
     
    end 
    
    def edit
      @genre = Genre.find(params[:id])
    end  
     
     
     private
       def genre_params
         params.require(:genre).permit(:name)
       end
     
     
        
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
  def new
    @item = Item.new
    @genres = Genre.all
  end 
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id), notice: "新商品登録完了！"
    else
     frash.now[:alert] = "もう一度入力し直してください"
     render "index"
    end
 
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
    
  end
  
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])

  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end
  
  
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?





  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
     @genres = Genre.all
     @items = Item.all
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_ditails_helper.rb
module Admin::OrderDitailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <div class="row">
      <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>
    </div>
    
    
    <%= form_with model:@customer, url: admin_customer_path, method: :PATCH, local:true do |f| %>
    <div class="col">
        
      
    </div>
    <div class="form-group row">
        <div class="col-md-3">会員ID</div>
        <div class="col-md-2"><%= @customer.id %></div>
    </div>
    <div class="form-group row">
        <%= f.label :氏名, class: "col-md-3" %>
        <%= f.text_field :last_name, class: "col-md-2 form-control" %>
        <%= f.text_field :first_name, class: "col-md-2 form-control ml-3" %>
    </div>
    <div class="form-group row"> 
        <%= f.label :フリガナ, class: "col-md-3" %>
        <%= f.text_field :last_name_kana, class: "col-md-2 form-control" %>
        <%= f.text_field :first_name_kana, class: "col-md-2 form-control ml-3" %>
    </div>
    <div class="form-group row">
        <%= f.label :郵便番号, class: "col-md-3" %>
        <%= f.text_field :postal_code, class: "col-md-5 form-control" %>
    </div>
    <div calss="form-group row">
        <%= f.label :住所, class: "col-md-3" %>
        <%= f.text_field :address, class: "col-md-5 form-cntrol" %>
    </div>
    <div class="form-group row">
        <%= f.label :電話番号, class: "col-md-3" %>
        <%= f.text_field :telephone_number, class: "col-md-5 form-control" %>
    </div>    
    <div class="form-group row">
        <%= f.label :メールアドレス, class: "col-md-3" %>
        <%= f.email_field :email, class: "col-md-5 form-control" %>
    </div>
    <div class="form-group row">
        <%= f.label :会員ステータス, class: "col-md-3" %>
        <label><%= f.radio_button :is_deleted?, false, checked: true %>有効</label>
        <label class="ml-3"><%= f.radio_button :is_deleted, true %>退会</label>
    </div>
      
      
    <div class="form-group row">
        <%= f.submit "変更を保存", class: "btn btn-success col-md-2 offset-3" %>
    </div>
   <% end %>
   </div>
      
      
      
      
       
    

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
   <h3>会員一覧</h3>
  </div>

<table class="table cart_items">
  <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
  </tr>
  <% @customers.each do |customer| %>
  <tr>
    <td><%= customer.id %></td>
    <td>
      <%= link_to admin_customer_path(customer) do %>
        <%= customer.last_name %><%= customer.first_name %>
      <% end %>
    </td>
    <td><%= customer.email %></td>
    <% if customer.is_deleted == false %>
      <td>有効</td>
    <% else %>
      <td>退会</td>
     <% end %>
  </tr>
  <% end %>
 </table>

</div>

app/views/admin/customers/show.html.erb
<div class="container">
    <div class="row">
      <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報詳細</h3>
    </div>
    
   <div class="row">
    <div class="col-md-12">
        <table class="table cart_items">
          <tr>
            <th style="width: 30%">会員ID</th>
            <td style="width: 70%"><%= @customer.id %></td>
          </tr>
          <tr>
             <th>氏名</th>
             <td><%= @customer.last_name %><%= @customer.first_name %></td>
          </tr>
          <tr>
             <th>フリガナ</th>
             <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
          </tr>
          <tr>
             <th>郵便番号</th>
             <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
             <th>住所</th>
             <td><%= @customer.address %></td>
          </tr>
          <tr>
             <th>電話番号</th>
             <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
             <th>メールアドレス</th>
             <td><%= @customer.email %></td>
          </tr>
          <tr>
             <th>会員ステータス</th>
             <% if @customer.is_deleted == false %>
              <td>有効</td>
             <% else %>
              <td>退会</td>
             <% end %>
          </tr>
         </table>
        </div>
       </div>
       
        
 <div class="row">
    <div class="col-md-5 clearfix">
        
     <div class="float-right"><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></div>      
    </div>
    <div class="col-md-7">
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-primary" %>    
    </div>
 </div>
 
</div>
    
       
          
          