config/routes.rb
Rails.application.routes.draw do
 
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'homes#top'
    resources :genres, except: [:show, :destroy, :new]
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders
    resources :order_details, only:[:update]
  end
  
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
  
  namespace :public do
    get 'orders/thanks', to: 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders
    resources :items, only: [:index, :show]
    resources :customers,except: [:new, :index]
    resources :addresses,except: [:new, :show]
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :cart_items, except: [:show, :new, :edit] 
    delete 'cart_items' => 'cart_items#destroy_all'
  end

end

app/models/address.rb
class Address < ApplicationRecord
 
  belongs_to :customer
  
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  
  def address_display
     '〒' + postal_code + ' ' + address + ' ' + name
  end  
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

 belongs_to :customer
 belongs_to :item
 
 
 
 def with_tax_price
   (price*1.1).floor
 end  
   
 #小計
 def subtotal
     item.with_tax_price*amount
 end
 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         
   has_many :cart_items, dependent: :destroy
   has_many :addresses, dependent: :destroy
   has_many :orders, dependent: :destroy 
   
   validates :last_name, presence: true
   validates :first_name, presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :postal_code, presence: true
   validates :telephone_number, presence: true
   validates :address, presence: true
   
   # def active_for_authentication?
   #   super && (is_deleted == true)
   #end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :ites,dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

 has_many :order_details, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 
 
 belongs_to :genre
 has_one_attached :image
 
  
  validates :name, presence: true
  validates :price, presence: true
  
  def with_tax_price
   (price * 1.1).floor
  end
  
  
  
end

app/models/order.rb
class Order < ApplicationRecord
 
 has_many :order_details, dependent: :destroy
 belongs_to :customer
 
 validates :postal_code, presence: true
 validates :address, presence: true
 validates :name, presence: true
 validates :way_of_paying, presence: true
    
 enum way_of_paying: { credit_card: 0, transfer: 1}
 enum recieve_status: { payment_waiting: 0, payment_finish:1, production: 2, ready_to_delivery: 3,delivery_finish: 4}
 
  
 def with_tax_price
   (price*1.1).floor
 end  
   
 #小計
 def subtotal
     item.with_tax_price*amount
 end
 
 def sum_order_price
   subtotal+shipping_fee
 end 
 
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    
    enum production_status:{ not_yet:0, waiting:1, working:2, complete:3}
    
    
     def subtotal
     item.with_tax_price*amount
     end
     
end     

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    
    def index
      @genre = Genre.new
      
      @genres = Genre.all
      
    end 
    
    def create
      @genre = Genre.new(genre_params)
     if @genre.save
      redirect_to admin_genres_path
     else
        flash[:alert]= "もう一度入力してね"
        @genres = Genre.all
        render:index
     end
     
    end 
    
    def edit
      @genre = Genre.find(params[:id])
    end  
     
     
     private
       def genre_params
         params.require(:genre).permit(:name)
       end
     
     
        
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
  def new
    @item = Item.new
    @genres = Genre.all
  end 
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id), notice: "新商品登録完了！"
    else
     frash.now[:alert] = "もう一度入力し直してください"
     render "index"
    end
 
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
    
  end
  
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])

  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end
  
  
      
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
   
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_status_params)

    
     if Order.recieve_status[@order.order_status]==1
      @order.order_details.each do |order_detail|
       order_detail.update(order_status:1)
      end
     end    
   redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?





  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
     @genres = Genre.all
     @items = Item.all
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_ditails_helper.rb
module Admin::OrderDitailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<main>
  <div class="container">
     <h3>ジャンル編集</h3>
  </div>
  
  <br>
  
  <div class="row">
    <div calss="col-2">
        ジャンル名
    </div>
    
    
    <%= form_with model:@genre,url: admin_genre_path(@genre),local:true do |f| %>
    <div calss="d-flex flex-row form-group">
      <div>
        <%= f.text_field :name,autofocus: true, id:"inputName", :class=> 'form-control' %>
      </div>
      
      <div>
        <%= f.submit "変更を保存" ,class: 'btn btn-success offset-md-2' %>
      </div>
    </div>
    <% end %>
    
    
   </div>
  </div>
 </main>
      
        
        
        
        
        
        
    
    
    

app/views/admin/genres/index.html.erb
<main>
    <div class="container">
        <div class="row">
          <span calss="heading">ジャンル一覧・追加</span>
        </div>
        
        <br> 
        
        
        <div class="row">
          <div class="col-2">
              ジャンル名
          </div>
          
          <%= form_with model:@genre,url: admin_genres_path, local:true do |f| %>
          <div class="d-flex flex-row form-group">
             <div>
               <%= f.text_field :name, :class => 'form-control' %>
             </div>
             
             <div>
               <%= f.submit "新規登録", class: 'btn btn-success offset-md2' %>
             </div>
          </div>
          <% end %>
         </div>
         
         <br>
         
         
         <div class="row">
           <div class="col-md-8">
              <table class="genres">
                <tr>
                 <th class="col-md-8">ジャンル</th>
                 <th class="col-md-4"></th>
                </tr>
                <% @genres.each do |genre| %>
                <tr>
                 <td><%= genre.name %></td>
                 <td>
                    <%= link_to edit_admin_genre_path(genre.id) do %>
                      <button type="button" class="btn btn-success">編集する</button>
                    <% end %>
                 </td>
                </tr>
                <% end %>
             </table>
            </div>
           </div>
          </div>
         </main>
                    
                    
                    
             
             
             
             
             

app/views/admin/items/edit.html.erb
<div class="container">
  <h3>商品編集</h3>
  <div class="row">
      
    <%= form_with model: @item, url: admin_item_path(@item.id), local: true do |f| %>
      <table>
         <tr>
           <th>商品画像</th>
           <td><%= f.file_field :image,accept: "image/*" %></td>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>商品名</th>
           <td><%= f.text_field :name %></td>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>商品説明</th>
           <td><%= f.text_area :introduction %></td>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>ジャンル</th>
           <td><%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "選択してください") %>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>税抜価格</th>
           <td><%= f.text_field :price %>円</td>
         </tr>
         <tr><td>&nbsp;</td></tr>
         <tr>
           <th>販売ステータス</th>
           <td>
              <%= f.radio_button :is_active, :true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "販売停止中" %>
           </td>
         </tr>
       </table>
       <br>
       <%= f.submit "変更を保存", class: 'btn btn-primary' %>
     <% end %>
  </div>
 </div>
              
               
               
               
               

app/views/admin/items/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-2">
         <h3>商品一覧</h3>
      </div>
      
      
      
      <div class="col-md-1 offset-md-9">
          <%= link_to new_admin_item_path do %>
            <i class="fas fa-plus-circle"></i>
          <% end %>
      </div>
    </div> 
       
       
      <div class="row">
          <table class="table cart_items">
            <tr>
              <th class="col-md-1">商品ID</th>
              <th class="col-md-3">商品名</th>
              <th class="col-md-2">税抜価格</th>
              <th class="col-md-2">ジャンル</th>
              <th class="col-md-2">ステータス</th>
            </tr>
            <% @items.each do |item| %>
            <tr>
              <td class="col-md-1"><%= item.id %></td>
              <td class="col-md-3"><%= link_to item.name, admin_item_path(item.id) %></td>
              <td class="col-md-2"><%= item.price %></td>
              <td class="col-md-2"><%= item.genre.name %></td>
              <td class="col-md-2"><%= item.is_active ? "販売中" : "販売停止中" %></td>
            </tr>
            <% end %>
          </table>
              
            
            
            
            

app/views/admin/items/new.html.erb
<main>
<div class="container">
  <h3>商品新規登録</h3>
  <div class="row">
      
     
     <%= form_with model:@item, url:admin_items_path,local: true do |f| %>
     <div class="col">
         
     </div>
       <table class="admin_items">
        <tr>
          <th>商品画像</th>
          <td><%= f.file_field:image,accept: "image/*" %></td>
        </tr>
        <tr>
          <th>商品名</th>
          <td><%= f.text_field:name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= f.text_area:introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= f.collection_select(:genre_id, @genres, :id, :name , prompt: "選択してください") %></td>
        </tr>
        <tr>
          <th>税抜価格</th>
          <td><%= f.text_field:price %>円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td class="col-md-3">
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中" %>
          </td>  
        </tr>
       </table>
       <br>
       <%= f.submit "新規登録" , class: 'btn btn-primary' %>
       <% end %>
      </div>
     </div>
</main>          
          
          

app/views/admin/items/show.html.erb
<div class="container">
  <h3>商品詳細</h3>
  <div class="row">
    <div class="col-md-4">
     <%= image_tag @item.image, size: "200x200" %>
    </div>
    <div class="col-md-5">
      <table class="table cart_items">
        <tr>
          <th>商品</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>  
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格<br> （税抜価格）</th>
          <td><%= @item.with_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>) 円</td> 
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td><%= @item.is_active ? "販売中" : "販売停止中" %></td>
        </tr>
      </table>
      <br>
       <%= link_to edit_admin_item_path(@item.id) do %>
        <button type="button" class="btn btn-success">
          編集する
         </button>
       <% end %>
      </div>
     </div>
    </div>

app/views/admin/orders/index.html.erb
<div class="p-5 ml-10 mr-10 w-80">
  <h2><span class="bg-gray">注文履歴一覧</span></h2>
  <table class="table">
    <thead class="bg-gray">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime("%Y/%m/%d"),admin_order_path(order.id) %></td>
          <td><%= order.customer.first_name+order.customer.last_name %></td>
          <td><%= order.order_details.sum(:amount) %></td>
          <td><%= Order.recieve_statuses_i18n[order.recieve_status] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


      
      
      
      

app/views/admin/orders/show.html.erb
<div calss="container">
    <div class="row">
        <div class="col-md-6 offset-md-1">
          <h2 class="my-4">注文履歴詳細</h2>
        </div>
    </div>
</div>
<div class="col-6">
  <table calss="order-customer">
    <tr>
      <th>購入者</th>
      <td><%= @order.name %></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td><%= @order.address %></td>
    </tr>
    <tr>
      <th>支払方法</th>
      <td><%= Order.way_of_payings_i18n[@order.way_of_paying] %></td>
    </tr>
    <tr>
      <%= form_with(model: @order, url:admin_order_path, local: true) do |f| %>
      <th>注文ステータス</th>
      <td>
        
        <%= f.select :recieve_status, Order.recieve_statuses.keys.map{|k| [I18n.t("enums.order.recieve_status.#{k}"),k]} ,{},{class: 'form-control'}  %>
        <%= f.submit "更新", class:"btn btn-success" %>
      </td>
      <% end %>
    </tr>
   </table>
  </div>
  <div class="row">
   <div class="col-7">
     <table class="table table-bordered">
       <thead>
         <th>商品名</th>
         <th>単価</th>
         <th>数量</th>
         <th>小計</th>
         <th>製作ステータス</th>
       </thead>
       <tbody>
         <% @order.order_details.each do |order_detail| %>
         <tr>
           <td><%= order_detail. item.name %></td>
           <td><%= (order_detail.purchase_price).to_s(:delimited) %> 円</td>
           <td><%= (order_detail.amount).to_s(:delimited) %> 個</td>
           <td><%= (order_detail.purchase_price*order_detail.amount).to_s(:delimited) %></td>
         </tr>  
             <div>
               
               
               <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id),method: :patch do |f| %>
                 <%= f.select :production_status, options_for_select([['着手不可'],['製作待ち'],['製作中'],['製作完了']],{:selected => order_detail.production_status}) %>
                 <%= f.submit "更新", class:"btn btn-success" %>
               <% end %>  
             </div>
           </td>  
         </tr>
         <% end %>
        </tbody>
      </table>
     </div>
     <div calss="col-4">
       <table>
         <tr>
           <th>商品合計</th>
           <td><%= (@order.billing_amount - @order.shipping_fee) %>円</td>
         </tr>
         <tr>
           <th>送料</th>
           <td><%= @order.shipping_fee %>円</td>
         </tr>  
         <tr>
            <th>請求金額合計</th> 
            <td><%= @order.billing_amount %>円</td>
         </tr>     
       </table>
     </div>
    </div>