config/routes.rb
Rails.application.routes.draw do
 
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: 'homes#top'
    resources :genres, except: [:show, :destroy, :new]
    resources :items, except: [:destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders
    resources :order_details, only:[:update]
  end
  
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
  
  namespace :public do
    get 'orders/thanks', to: 'orders#thanks'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders
    resources :items, only: [:index, :show]
    resources :customers,except: [:new, :index]
    resources :addresses,except: [:new, :show]
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :cart_items, except: [:show, :new, :edit] 
    delete 'cart_items' => 'cart_items#destroy_all'
  end

end

app/models/address.rb
class Address < ApplicationRecord
 
  belongs_to :customer
  
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  
  def address_display
     '〒' + postal_code + ' ' + address + ' ' + name
  end  
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

 belongs_to :customer
 belongs_to :item
 
 
 
 def with_tax_price
   (price*1.1).floor
 end  
   
 #小計
 def subtotal
     item.with_tax_price*amount
 end
 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         
   has_many :cart_items, dependent: :destroy
   has_many :addresses, dependent: :destroy
   has_many :orders, dependent: :destroy 
   
   validates :last_name, presence: true
   validates :first_name, presence: true
   validates :last_name_kana, presence: true
   validates :first_name_kana, presence: true
   validates :postal_code, presence: true
   validates :telephone_number, presence: true
   validates :address, presence: true
   
   # def active_for_authentication?
   #   super && (is_deleted == true)
   #end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :ites,dependent: :destroy
    
    validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

 has_many :order_details, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 
 
 belongs_to :genre
 has_one_attached :image
 
  
  validates :name, presence: true
  validates :price, presence: true
  
  def with_tax_price
   (price * 1.1).floor
  end
  
  
  
end

app/models/order.rb
class Order < ApplicationRecord
 
 has_many :order_details, dependent: :destroy
 belongs_to :customer
 
 validates :postal_code, presence: true
 validates :address, presence: true
 validates :name, presence: true
 validates :way_of_paying, presence: true
    
 enum way_of_paying: { credit_card: 0, transfer: 1}
 enum recieve_status: { payment_waiting: 0, payment_finish:1, production: 2, ready_to_delivery: 3,delivery_finish: 4}
 
  
 def with_tax_price
   (price*1.1).floor
 end  
   
 #小計
 def subtotal
     item.with_tax_price*amount
 end
 
 def sum_order_price
   subtotal+shipping_fee
 end 
 
 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    
    enum production_status:{ not_yet:0, waiting:1, working:2, complete:3}
    
    
     def subtotal
     item.with_tax_price*amount
     end
     
end     

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
  def new
    @item = Item.new
    @genres = Genre.all
  end 
  
  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admin_item_path(@item.id), notice: "新商品登録完了！"
    else
     frash.now[:alert] = "もう一度入力し直してください"
     render "index"
    end
 
  end
  
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
    
  end
  
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])

  end
  
  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end
  
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image)
  end
  
  
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?





  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
     @genres = Genre.all
     @items = Item.all
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
     
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class-"container">
         <a class="navbar-brand p-3" href="/"><%= image_tag 'logo.png', :size =>'80x80' %></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
         </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
  
        
        <% if customer_signed_in? %>
              <p>ようこそ<%= current_customer.last_name %>さん！</p>
            <% end %>
    <ul class="navbar-nav ml-auto">
       <% if customer_signed_in? %>
       <li class="navbar-link"><%= link_to "マイページ", public_customer_path(current_customer), class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "商品一覧", public_items_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "カート", public_cart_items_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %></li
       <% elsif admin_signed_in? %>
       <li class="navbar-link"><%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "注文履歴一覧", admin_orders_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %></li>
      <% else %>
       <li class="navbar-link"><%= link_to "About", about_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "商品一覧", public_items_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %></li>
       <li class="navbar-link"><%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %></li>
      <% end %>
    </ul>
     </div>
    </div>
   </nav>
   </header>
   <main class="mb-auto">
     <p id="notice"><%= notice %></p>
    <%= yield %>
    </main>
   
   <footer class="bg-dark text-white">
      <div class="container">
        <p>©ながのケーキ</p>
      </div>
    </footer>
  </body>
</html>